# Generated by Django 2.2.4 on 2019-08-14 13:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('is_public', models.BooleanField(default=False)),
                ('recipe_type', models.CharField(choices=[('BREAKFAST', 'Breakfast'), ('LUNCH', 'Lunch'), ('DINNER', 'Dinner'), ('DESSERT', 'Dessert')], max_length=255)),
                ('prep_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_time', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('cook_temp', models.IntegerField()),
                ('temp_scale', models.CharField(choices=[('FARENHEIT', 'Farenheit'), ('CELSIUS', 'Celsius')], max_length=255)),
                ('recipe_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('recipe_unit', models.CharField(max_length=255)),
                ('personal_notes', models.TextField()),
            ],
        ),
    ]
